version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db # volumn is used to store persist data or share data between the container and the host system.

  # Node api service
  api:
    image: nodeapp
    ports:
      - 3030:3030
    depends_on: # depends_on ensures mongo_db container running first and then starts the api container.
      - mongo_db

volumes:
  mongo_data: {}
